package content.global.skill.magic.spells.modern

import shared.consts.Animations
import shared.consts.Graphics
import shared.consts.Items
import shared.consts.Sounds

/**
 * Represents the enchant spell effects.
 */
enum class EnchantSpellEffect(val itemId: Int, val animation: Int, val graphic: Int, val sound: Int) {
    SAPPHIRE_AMULET(Items.SAPPHIRE_AMULET_1694, Animations.ENCHANT_JEWEL_719, Graphics.ENCHANT_1_114, Sounds.ENCHANT_SAPPHIRE_AMULET_136),
    SAPPHIRE_NECKLACE(Items.SAPPHIRE_NECKLACE_1656, Animations.ENCHANT_JEWEL_719, Graphics.ENCHANT_1_114, Sounds.ENCHANT_SAPPHIRE_AMULET_136),
    SAPPHIRE_RING(Items.SAPPHIRE_RING_1637, Animations.ENCHANT_JEWEL_722, Graphics.ENCHANT_RING_238, Sounds.ENCHANT_SAPPHIRE_RING_147),
    SAPPHIRE_BRACELET(Items.SAPPHIRE_BRACELET_11072, Animations.ENCHANT_JEWEL_722, Graphics.ENCHANT_RING_238, Sounds.ENCHANT_SAPPHIRE_RING_147),

    EMERALD_AMULET(Items.EMERALD_AMULET_1696, Animations.ENCHANT_JEWEL_719, Graphics.ENCHANT_1_114, Sounds.ENCHANT_EMERALD_AMULET_141),
    EMERALD_NECKLACE(Items.EMERALD_NECKLACE_1658, Animations.ENCHANT_JEWEL_719, Graphics.ENCHANT_1_114, Sounds.ENCHANT_EMERALD_AMULET_141),
    EMERALD_RING(Items.EMERALD_RING_1639, Animations.ENCHANT_JEWEL_722, Graphics.ENCHANT_RING_238, Sounds.ENCHANT_EMERALD_RING_142),
    EMERALD_BRACELET(Items.EMERALD_BRACELET_11076, Animations.ENCHANT_JEWEL_722, Graphics.ENCHANT_RING_238, Sounds.ENCHANT_EMERALD_RING_142),
    ENCHANTED_SICKLE(Items.SILVER_SICKLE_EMERALDB_13155, Animations.BREAK_SPELL_TABLET_B_4070, Graphics.SICKLE_ENCHANTMENT_1604, Sounds.ENCHANT_EMERALD_RING_142),

    RUBY_AMULET(Items.RUBY_AMULET_1698, Animations.ENCHANT_JEWEL_720, Graphics.ENCHANT_2_115, Sounds.ENCHANT_RUBY_AMULET_145),
    RUBY_NECKLACE(Items.RUBY_NECKLACE_1660, Animations.ENCHANT_JEWEL_720, Graphics.ENCHANT_2_115, Sounds.ENCHANT_RUBY_AMULET_145),
    RUBY_RING(Items.RUBY_RING_1641, Animations.ENCHANT_JEWEL_722, Graphics.ENCHANT_RING_238, Sounds.ENCHANT_RUBY_RING_146),
    RUBY_BRACELET(Items.RUBY_BRACELET_11085, Animations.ENCHANT_JEWEL_722, Graphics.ENCHANT_RING_238, Sounds.ENCHANT_RUBY_RING_146),

    DIAMOND_AMULET(Items.DIAMOND_AMULET_1700, Animations.ENCHANT_JEWEL_720, Graphics.ENCHANT_2_115, Sounds.ENCHANT_DIAMOND_AMULET_137),
    DIAMOND_NECKLACE(Items.DIAMOND_NECKLACE_1662, Animations.ENCHANT_JEWEL_720, Graphics.ENCHANT_2_115, Sounds.ENCHANT_DIAMOND_AMULET_137),
    DIAMOND_RING(Items.DIAMOND_RING_1643, Animations.ENCHANT_JEWEL_722, Graphics.ENCHANT_RING_238, Sounds.ENCHANT_DIAMOND_RING_138),
    DIAMOND_BRACELET(Items.DIAMOND_BRACELET_11092, Animations.ENCHANT_JEWEL_722, Graphics.ENCHANT_RING_238, Sounds.ENCHANT_DIAMOND_RING_138),

    DRAGON_AMULET(Items.DRAGONSTONE_AMMY_1702, Animations.ENCHANT_JEWEL_721, Graphics.ENCHANT_3_116, Sounds.ENCHANT_DRAGON_AMULET_139),
    DRAGON_NECKLACE(Items.DRAGON_NECKLACE_1664, Animations.ENCHANT_JEWEL_721, Graphics.ENCHANT_3_116, Sounds.ENCHANT_DRAGON_AMULET_139),
    DRAGON_RING(Items.DRAGONSTONE_RING_1645, Animations.ENCHANT_JEWEL_722, Graphics.ENCHANT_RING_238, Sounds.ENCHANT_DRAGON_RING_140),
    DRAGON_BRACELET(Items.DRAGON_BRACELET_11115, Animations.ENCHANT_JEWEL_722, Graphics.ENCHANT_RING_238, Sounds.ENCHANT_DRAGON_RING_140),

    ONYX_AMULET(Items.ONYX_AMULET_6581, Animations.ENCHANT_JEWEL_721, Graphics.ONYX_AMMY_ENCHANTING_452, Sounds.ENCHANT_ONYX_AMULET_143),
    ONYX_NECKLACE(Items.ONYX_NECKLACE_6565, Animations.ENCHANT_JEWEL_721, Graphics.ONYX_AMMY_ENCHANTING_452, Sounds.ENCHANT_ONYX_AMULET_143),
    ONYX_RING(Items.ONYX_RING_6575, Animations.ENCHANT_JEWEL_722, Graphics.ENCHANT_RING_238, Sounds.ENCHANT_ONYX_RING_144),
    ONYX_BRACELET(Items.ONYX_BRACELET_11130, Animations.ENCHANT_JEWEL_722, Graphics.ENCHANT_RING_238, Sounds.ENCHANT_ONYX_RING_144);

    companion object {
        private val lookup = values().associateBy(EnchantSpellEffect::itemId)
        fun fromItemId(id: Int): EnchantSpellEffect? = lookup[id]
    }
}