package content.global.skill.magic.spells.modern

import content.global.skill.magic.spells.ModernSpells
import content.global.skill.magic.spells.SpellProjectile
import core.game.node.entity.combat.spell.Runes
import core.game.node.entity.combat.spell.SpellType
import core.game.node.entity.impl.Projectile
import core.game.node.item.Item
import core.game.world.update.flag.context.Graphics
import shared.consts.Sounds
import shared.consts.Graphics as Gfx

enum class ModernSpellDefinition(val type: SpellType, val button: Int, val level: Int, val xp: Double, val sound: Int, val impactSound: Int, val start: Graphics, val projectile: Projectile, val end: Graphics, val runes: Array<Item>) {
    AIR_STRIKE(SpellType.STRIKE, ModernSpells.AIR_STRIKE, 1, 5.5, Sounds.WINDSTRIKE_CAST_AND_FIRE_220, Sounds.WINDSTRIKE_HIT_221, Graphics(Gfx.WIND_STRIKE_CAST_90, 96), SpellProjectile.create(Gfx.WIND_STRIKE_PROJECTILE_91), Graphics(Gfx.WIND_STRIKE_IMPACT_92, 96), arrayOf(Runes.MIND_RUNE.getItem(1), Runes.AIR_RUNE.getItem(1))),
    AIR_BOLT(SpellType.BOLT, ModernSpells.AIR_BOLT, 17, 13.5, Sounds.WINDBOLT_CAST_AND_FIRE_218, Sounds.WINDBOLT_HIT_219, Graphics(Gfx.WIND_BOLT_CAST_117, 96), SpellProjectile.create(Gfx.WIND_BOLT_PROJECTILE_118), Graphics(Gfx.WIND_BOLT_IMPACT_119, 96), arrayOf(Runes.CHAOS_RUNE.getItem(1), Runes.AIR_RUNE.getItem(2))),
    AIR_BLAST(SpellType.BLAST, ModernSpells.AIR_BLAST, 41, 25.5, Sounds.WINDBLAST_CAST_AND_FIRE_216, Sounds.WINDBLAST_HIT_217, Graphics(Gfx.WIND_BLAST_CAST_132, 96), SpellProjectile.create(Gfx.WIND_BLAST_PROJECTILE_133), Graphics(Gfx.WIND_BLAST_IMPACT_134, 96), arrayOf(Runes.DEATH_RUNE.getItem(1), Runes.AIR_RUNE.getItem(3))),
    AIR_WAVE(SpellType.WAVE, ModernSpells.AIR_WAVE, 62, 36.0, Sounds.WINDWAVE_CAST_AND_FIRE_222, Sounds.WINDWAVE_HIT_223, Graphics(Gfx.WIND_WAVE_CAST_158, 96), SpellProjectile.create(Gfx.WIND_WAVE_PROJECTILE_159), Graphics(Gfx.WIND_WAVE_IMPACT_160, 96), arrayOf(Runes.BLOOD_RUNE.getItem(1), Runes.AIR_RUNE.getItem(5))),

    EARTH_STRIKE(SpellType.STRIKE, ModernSpells.EARTH_STRIKE, 9, 9.5, Sounds.EARTHSTRIKE_CAST_AND_FIRE_132, 133, Graphics(Gfx.EARTH_STRIKE_CAST_96, 96), SpellProjectile.create(Gfx.EARTH_STRIKE_PROJECTILE_97), Graphics(Gfx.EARTH_STRIKE_IMPACT_98, 96), arrayOf(Runes.MIND_RUNE.getItem(1), Runes.EARTH_RUNE.getItem(2), Runes.AIR_RUNE.getItem(1))),
    EARTH_BOLT(SpellType.BOLT, ModernSpells.EARTH_BOLT, 29, 19.5, Sounds.EARTHBOLT_CAST_AND_FIRE_130, 131, Graphics(Gfx.EARTH_BOLT_CAST_123, 96), SpellProjectile.create(Gfx.EARTH_BOLT_PROJECTILE_124), Graphics(Gfx.EARTH_BOLT_IMPACT_125, 96), arrayOf(Runes.CHAOS_RUNE.getItem(1), Runes.EARTH_RUNE.getItem(3), Runes.AIR_RUNE.getItem(2))),
    EARTH_BLAST(SpellType.BLAST, ModernSpells.EARTH_BLAST, 53, 31.5, Sounds.EARTHBLAST_CAST_AND_FIRE_128, 129, Graphics(Gfx.EARTH_BLAST_CAST_138, 96), SpellProjectile.create(Gfx.EARTH_BLAST_PROJECTILE_139), Graphics(Gfx.EARTH_BLAST_IMPACT_140, 96), arrayOf(Runes.DEATH_RUNE.getItem(1), Runes.EARTH_RUNE.getItem(4), Runes.AIR_RUNE.getItem(3))),
    EARTH_WAVE(SpellType.WAVE, ModernSpells.EARTH_WAVE, 70, 40.0, Sounds.EARTHWAVE_CAST_AND_FIRE_134, 135, Graphics(Gfx.EARTH_WAVE_CAST_164, 96), SpellProjectile.create(Gfx.EARTH_WAVE_PROJECTILE_165), Graphics(Gfx.EARTH_WAVE_IMPACT_166, 96), arrayOf(Runes.BLOOD_RUNE.getItem(1), Runes.EARTH_RUNE.getItem(7), Runes.AIR_RUNE.getItem(5))),

    WATER_STRIKE(SpellType.STRIKE, ModernSpells.WATER_STRIKE, 5, 7.5, Sounds.WATERSTRIKE_CAST_AND_FIRE_211, 212, Graphics(Gfx.WATER_STRIKE_CAST_93, 96), SpellProjectile.create(Gfx.WATER_STRIKE_PROJECTILE_94), Graphics(Gfx.WATER_STRIKE_IMPACT_95, 96), arrayOf(Runes.MIND_RUNE.getItem(1), Runes.WATER_RUNE.getItem(1), Runes.AIR_RUNE.getItem(1))),
    WATER_BOLT(SpellType.BOLT, ModernSpells.WATER_BOLT, 23, 16.5, Sounds.WATERBOLT_CAST_AND_FIRE_209, 210, Graphics(Gfx.WATER_BOLT_CAST_120, 96), SpellProjectile.create(Gfx.WATER_BOLT_PROJECTILE_121), Graphics(Gfx.WATER_BOLT_IMPACT_122, 96), arrayOf(Runes.CHAOS_RUNE.getItem(1), Runes.WATER_RUNE.getItem(2), Runes.AIR_RUNE.getItem(2))),
    WATER_BLAST(SpellType.BLAST, ModernSpells.WATER_BLAST, 47, 28.5, Sounds.WATERBLAST_CAST_AND_FIRE_207, 208, Graphics(Gfx.WATER_BLAST_CAST_135, 96), SpellProjectile.create(Gfx.WATER_BLAST_PROJECTILE_136), Graphics(Gfx.WATER_BLAST_IMPACT_137, 96), arrayOf(Runes.DEATH_RUNE.getItem(1), Runes.WATER_RUNE.getItem(3), Runes.AIR_RUNE.getItem(3))),
    WATER_WAVE(SpellType.WAVE, ModernSpells.WATER_WAVE, 65, 37.5, Sounds.WATERWAVE_CAST_AND_FIRE_213, 214, Graphics(Gfx.WATER_WAVE_CAST_161, 96), SpellProjectile.create(Gfx.WATER_WAVE_PROJECTILE_162), Graphics(Gfx.WATER_WAVE_IMPACT_163, 96), arrayOf(Runes.BLOOD_RUNE.getItem(1), Runes.WATER_RUNE.getItem(7), Runes.AIR_RUNE.getItem(5))),

    FIRE_STRIKE(SpellType.STRIKE, ModernSpells.FIRE_STRIKE, 13, 11.5, Sounds.FIRESTRIKE_CAST_AND_FIRE_160, 161, Graphics(Gfx.FIRE_STRIKE_CAST_99, 96), SpellProjectile.create(Gfx.FIRE_STRIKE_PROJECTILE_100), Graphics(Gfx.FIRE_STRIKE_IMPACT_101, 96), arrayOf(Runes.MIND_RUNE.getItem(1), Runes.FIRE_RUNE.getItem(3), Runes.AIR_RUNE.getItem(2))),
    FIRE_BOLT(SpellType.BOLT, ModernSpells.FIRE_BOLT, 35, 22.5, Sounds.FIREBOLT_CAST_AND_FIRE_157, 158, Graphics(Gfx.FIRE_BOLT_CAST_126, 96), SpellProjectile.create(Gfx.FIRE_BOLT_PROJECTILE_127), Graphics(Gfx.FIRE_BOLT_IMPACT_128, 96), arrayOf(Runes.CHAOS_RUNE.getItem(1), Runes.FIRE_RUNE.getItem(4), Runes.AIR_RUNE.getItem(3))),
    FIRE_BLAST(SpellType.BLAST, ModernSpells.FIRE_BLAST, 59, 34.5, Sounds.FIREBLAST_CAST_AND_FIRE_155, 156, Graphics(Gfx.FIRE_BLAST_CAST_129, 96), SpellProjectile.create(Gfx.FIRE_BLAST_PROJECTILE_130), Graphics(Gfx.FIRE_BLAST_IMPACT_131, 96), arrayOf(Runes.DEATH_RUNE.getItem(1), Runes.FIRE_RUNE.getItem(5), Runes.AIR_RUNE.getItem(4))),
    FIRE_WAVE(SpellType.WAVE, ModernSpells.FIRE_WAVE, 75, 42.5, Sounds.FIREWAVE_CAST_AND_FIRE_162, 163, Graphics(Gfx.FIRE_WAVE_CAST_155, 96), SpellProjectile.create(Gfx.FIRE_WAVE_PROJECTILE_156), Graphics(Gfx.FIRE_WAVE_IMPACT_157, 96), arrayOf(Runes.BLOOD_RUNE.getItem(1), Runes.FIRE_RUNE.getItem(7), Runes.AIR_RUNE.getItem(5))),

    BIND(SpellType.BIND, ModernSpells.BIND, 20, 30.0, Sounds.BIND_CAST_101, Sounds.BIND_IMPACT_99, Graphics(Gfx.BIND_CAST_177, 96), SpellProjectile.create(Gfx.BIND_PROJECTILE_178), Graphics(Gfx.BIND_IMPACT_179, 96), arrayOf(Runes.NATURE_RUNE.getItem(2), Runes.EARTH_RUNE.getItem(3), Runes.WATER_RUNE.getItem(3))),
    SNARE(SpellType.SNARE, ModernSpells.SNARE, 50, 60.0, Sounds.SNARE_CAST_AND_FIRE_3003, Sounds.SNARE_IMPACT_3002, Graphics(Gfx.BIND_CAST_177, 96), SpellProjectile.create(Gfx.BIND_PROJECTILE_178), Graphics(Gfx.SNARE_IMPACT_180, 96), arrayOf(Runes.NATURE_RUNE.getItem(3), Runes.EARTH_RUNE.getItem(4), Runes.WATER_RUNE.getItem(4))),
    ENTANGLE(SpellType.ENTANGLE, ModernSpells.ENTANGLE, 79, 89.0, Sounds.ENTANGLE_CAST_AND_FIRE_151, Sounds.ENTANGLE_HIT_153, Graphics(Gfx.BIND_CAST_177, 96), SpellProjectile.create(Gfx.BIND_PROJECTILE_178), Graphics(Gfx.ENTANGLE_IMPACT_181, 96), arrayOf(Runes.NATURE_RUNE.getItem(4), Runes.EARTH_RUNE.getItem(5), Runes.WATER_RUNE.getItem(5))),

    CONFUSE(SpellType.CONFUSE, ModernSpells.CONFUSE, 3, 13.0, Sounds.CONFUSE_CAST_AND_FIRE_119, Sounds.CONFUSE_HIT_121, Graphics(Gfx.CONFUSE_CAST_102, 96), SpellProjectile.create(Gfx.CONFUSE_PROJECTILE_103), Graphics(Gfx.CONFUSE_IMPACT_104, 96), arrayOf(Runes.BODY_RUNE.getItem(1), Runes.EARTH_RUNE.getItem(2), Runes.WATER_RUNE.getItem(3))),
    WEAKEN(SpellType.WEAKEN, ModernSpells.WEAKEN, 11, 21.0, Sounds.WEAKEN_CAST_AND_FIRE_3011, Sounds.WEAKEN_HIT_3010, Graphics(Gfx.WEAKEN_CAST_105, 96), SpellProjectile.create(Gfx.WEAKEN_PROJECTILE_106), Graphics(Gfx.WEAKEN_IMPACT_107, 96), arrayOf(Runes.BODY_RUNE.getItem(1), Runes.EARTH_RUNE.getItem(2), Runes.WATER_RUNE.getItem(3))),
    CURSE(SpellType.CURSE, ModernSpells.CURSE, 19, 29.0, Sounds.CURSE_CAST_AND_FIRE_127, Sounds.CURSE_HIT_126, Graphics(Gfx.CURSE_CAST_108, 96), SpellProjectile.create(Gfx.CURSE_PROJECTILE_109), Graphics(Gfx.CURSE_IMPACT_110, 96), arrayOf(Runes.BODY_RUNE.getItem(1), Runes.EARTH_RUNE.getItem(3), Runes.WATER_RUNE.getItem(2))),
    VULNERABILITY(SpellType.VULNERABILITY, ModernSpells.VULNERABILITY, 66, 76.0, Sounds.VULNERABILITY_CAST_AND_FIRE_3009, Sounds.VULNERABILITY_IMPACT_3008, Graphics(Gfx.VULNERABILITY_CAST_167, 96), SpellProjectile.create(Gfx.VULNERABILITY_PROJECTILE_168), Graphics(Gfx.VULNERABILITY_IMPACT_169, 96, 1), arrayOf(Runes.SOUL_RUNE.getItem(1), Runes.EARTH_RUNE.getItem(5), Runes.WATER_RUNE.getItem(5))),
    ENFEEBLE(SpellType.ENFEEBLE, ModernSpells.ENFEEBLE, 73, 83.0, Sounds.ENFEEBLE_CAST_AND_FIRE_148, Sounds.ENFEEBLE_HIT_150, Graphics(Gfx.ENFEEBLE_CAST_170, 96), SpellProjectile.create(Gfx.ENFEEBLE_PROJECTILE_171), Graphics(Gfx.ENFEEBLE_IMPACT_172, 96), arrayOf(Runes.SOUL_RUNE.getItem(1), Runes.EARTH_RUNE.getItem(8), Runes.WATER_RUNE.getItem(8))),
    STUN(SpellType.STUN, ModernSpells.STUN, 80, 90.0, Sounds.STUN_CAST_AND_FIRE_3004, Sounds.STUN_IMPACT_3005, Graphics(Gfx.STUN_CAST_173, 96), SpellProjectile.create(Gfx.STUN_PROJECTILE_174), Graphics(Gfx.WEAKEN_IMPACT_107, 96), arrayOf(Runes.SOUL_RUNE.getItem(1), Runes.EARTH_RUNE.getItem(12), Runes.WATER_RUNE.getItem(12)))
}